name: Validate Required Secrets

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-secrets:
    # 1) Не запускаем на форках (там секретов точно нет)
    # 2) И если в репозитории вообще НЕ настроены базовые секреты (BASE_URL или BOT_ID)
    if: >
      github.event.pull_request.head.repo.full_name == github.repository &&
      (secrets.BASE_URL != '' || secrets.BOT_ID != '')
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN:     ${{ secrets.TELEGRAM_TOKEN }}
      CRYPTOBOT_TOKEN:    ${{ secrets.CRYPTOBOT_TOKEN }}
      BASE_URL:           ${{ secrets.BASE_URL }}
      BOT_ID:             ${{ secrets.BOT_ID }}
      VIP_CHANNEL_ID:     ${{ secrets.VIP_CHANNEL_ID }}
      CHAT_GROUP_ID:      ${{ secrets.CHAT_GROUP_ID }}
      LIFE_CHANNEL_ID:    ${{ secrets.LIFE_CHANNEL_ID }}
      LOG_CHANNEL_ID:     ${{ secrets.LOG_CHANNEL_ID }}
      LUXURY_CHANNEL_ID:  ${{ secrets.LUXURY_CHANNEL_ID }}
      LIFE_URL:           ${{ secrets.LIFE_URL }}
      HISTORY_GROUP_ID:   ${{ secrets.HISTORY_GROUP_ID }}
      POST_PLAN_GROUP_ID: ${{ secrets.POST_PLAN_GROUP_ID }}
    steps:
      - name: Check required secrets
        shell: bash
        run: |
          missing=0
          for v in TELEGRAM_TOKEN CRYPTOBOT_TOKEN BASE_URL BOT_ID VIP_CHANNEL_ID CHAT_GROUP_ID LIFE_CHANNEL_ID LOG_CHANNEL_ID LUXURY_CHANNEL_ID LIFE_URL HISTORY_GROUP_ID POST_PLAN_GROUP_ID; do
            if [ -z "${!v}" ]; then
              echo "::error title=Missing secret::${v}"
              missing=1
            else
              echo "✅ ${v} present"
            fi
          done
          exit $missing

  # Информационный шаг, чтобы было видно, почему джоб «серый», когда секретов нет
  no-secrets-info:
    if: >
      github.event.pull_request.head.repo.full_name == github.repository &&
      !(secrets.BASE_URL != '' || secrets.BOT_ID != '')
    runs-on: ubuntu-latest
    steps:
      - run: echo "No repo secrets configured — skipping secrets validation (secrets are kept in Northflank)."
