name: Validate Required Secrets (soft)

on:
  pull_request:
  workflow_dispatch:

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    # Не запускать на PR из форков: там секретов по определению нет
    if: ${{ !github.event.pull_request.head.repo.fork }}
    env:
      # Секреты, если они вдруг есть в репозитории
      TELEGRAM_TOKEN:     ${{ secrets.TELEGRAM_TOKEN }}
      CRYPTOBOT_TOKEN:    ${{ secrets.CRYPTOBOT_TOKEN }}
      WEBHOOK_URL:        ${{ secrets.WEBHOOK_URL }}
      VIP_CHANNEL_ID:     ${{ secrets.VIP_CHANNEL_ID }}
      CHAT_GROUP_ID:      ${{ secrets.CHAT_GROUP_ID }}
      LIFE_CHANNEL_ID:    ${{ secrets.LIFE_CHANNEL_ID }}
      LOG_CHANNEL_ID:     ${{ secrets.LOG_CHANNEL_ID }}
      LUXURY_CHANNEL_ID:  ${{ secrets.LUXURY_CHANNEL_ID }}
      LIFE_URL:           ${{ secrets.LIFE_URL }}
      HISTORY_GROUP_ID:   ${{ secrets.HISTORY_GROUP_ID }}
      POST_PLAN_GROUP_ID: ${{ secrets.POST_PLAN_GROUP_ID }}

      # Необязательно: если когда‑нибудь захочешь хранить ТОЛЬКО переменные (не секреты) —
      # можно подсунуть BASE_URL и BOT_ID как repo Variables (Settings → Variables), а из них собрать WEBHOOK_URL.
      BASE_URL_VAR: ${{ vars.BASE_URL }}
      BOT_ID_VAR:   ${{ vars.BOT_ID }}

    steps:
      - name: Warn on missing secrets (do not fail)
        shell: bash
        run: |
          set -e

          # Если WEBHOOK_URL не задан как секрет, но есть BASE_URL/BOT_ID в Variables — соберём его «на лету».
          if [[ -z "${WEBHOOK_URL}" && -n "${BASE_URL_VAR}" && -n "${BOT_ID_VAR}" ]]; then
            WEBHOOK_URL="${BASE_URL_VAR%/}/webhook/${BOT_ID_VAR}"
            echo "::notice title=WEBHOOK_URL synthesized::Using ${WEBHOOK_URL}"
          fi

          required=(
            TELEGRAM_TOKEN
            CRYPTOBOT_TOKEN
            WEBHOOK_URL
            VIP_CHANNEL_ID
            CHAT_GROUP_ID
            LIFE_CHANNEL_ID
            LOG_CHANNEL_ID
            LUXURY_CHANNEL_ID
            LIFE_URL
            HISTORY_GROUP_ID
            POST_PLAN_GROUP_ID
          )

          missing=0
          for v in "${required[@]}"; do
            if [[ -z "${!v}" ]]; then
              echo "::warning title=Missing secret::${v} is not set in GitHub"
              ((missing+=1))
            else
              echo "✅ ${v} present"
            fi
          done

          echo "Summary: $missing missing item(s). This is a SOFT check and will not fail the job."
          # Не падаем: всегда выходим с 0
          exit 0
