name: Validate Required Secrets

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-secrets:
    # не запускать на PR из форков (там секретов нет)
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN:     ${{ secrets.TELEGRAM_TOKEN }}
      CRYPTOBOT_TOKEN:    ${{ secrets.CRYPTOBOT_TOKEN }}
      BASE_URL:           ${{ secrets.BASE_URL }}       # <-- было WEBHOOK_URL
      VIP_CHANNEL_ID:     ${{ secrets.VIP_CHANNEL_ID }}
      CHAT_GROUP_ID:      ${{ secrets.CHAT_GROUP_ID }}
      LIFE_CHANNEL_ID:    ${{ secrets.LIFE_CHANNEL_ID }}
      LOG_CHANNEL_ID:     ${{ secrets.LOG_CHANNEL_ID }}
      LUXURY_CHANNEL_ID:  ${{ secrets.LUXURY_CHANNEL_ID }}
      LIFE_URL:           ${{ secrets.LIFE_URL }}
      HISTORY_GROUP_ID:   ${{ secrets.HISTORY_GROUP_ID }}
      POST_PLAN_GROUP_ID: ${{ secrets.POST_PLAN_GROUP_ID }}
    steps:
      - name: Check required secrets
        shell: bash
        run: |
          missing=0
          for v in TELEGRAM_TOKEN CRYPTOBOT_TOKEN BASE_URL VIP_CHANNEL_ID CHAT_GROUP_ID LIFE_CHANNEL_ID LOG_CHANNEL_ID LUXURY_CHANNEL_ID LIFE_URL HISTORY_GROUP_ID POST_PLAN_GROUP_ID; do
            if [ -z "${!v}" ]; then
              echo "::error title=Missing secret::${v}"
              missing=1
            else
              echo "✅ ${v} present"
            fi
          done
          exit $missing
