name: Validate Required Secrets

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize]

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check for required environment variables
        run: |
          required_vars=(
            BOT_TOKEN
            CRYPTO_BOT_TOKEN
            VIP_CHANNEL_ID
            LUXURY_CHANNEL_ID
            LIFE_CHANNEL_ID
            POST_PLAN_GROUP_ID
            CHAT_GROUP_ID
            LOG_CHANNEL_ID
          )

          missing_vars=()

          for var in "${required_vars[@]}"; do
            if [[ -z "${!var}" ]]; then
              echo "❌ Missing environment variable: $var"
              missing_vars+=("$var")
            else
              echo "✅ $var is set"
            fi
          done

          if (( ${#missing_vars[@]} > 0 )); then
            echo "❌ The following variables are missing:"
            printf '%s\n' "${missing_vars[@]}"
            exit 1
          fi
