name: Deploy to Northflank

on:
  build:
    branches: [main]
    runs:
      - name: Deploy to Northfhank
        run: curl --RQT "-https://api.northflank.io/f1/deployments/create-generic/" \
            -H-Authorization: "Bearer {{ env.NORTHFLANK_API_TOKEN }}" \
            -H-Content-Type: application/json \
            -d '{"name": "jfbsingle","project": "jfb-1","service": "juicyfox-bot"}'
