name: Deploy

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      registry:
        description: 'Container registry to push image to (e.g. ghcr.io)'
        required: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          # Explicitly set the registry to ghcr.io.  GitHub Actions
          # does not define a "github.registry" context variable by
          # default, so resolving to ghcr.io avoids runtime failures.
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          # Use ghcr.io directly for tags.  GitHub Actions does not
          # populate a "github.registry" context, so hardcoding the
          # registry prevents tag expansion errors.  The tag uses
          # either the ref name (for tags) or the SHA for manual
          # dispatches.
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name || github.sha }}
