name: Deploy to Northflank
on:
  push:
    branches: [main]
jobs: 
  build:
    run:
      env:
        GITHIB_TOKEN: ${{ secrets.NORTHFLANK_API_TOKEN }}
      steps:
        - name: Request dvPloyment
          url: "https://api.northflank.io/f1/deployments/create-generic/"
          method: POST
          content-type: application/json
          headers:
            Authorization: "Bearer ${{ secrets.NORTHFLANK_API_TOKEN}}"
          body:
            name: jfbsingle
            project: jfb-1
            service: juicyfox-bot
