name: Deploy to Northflank

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Northflank
        run: curl --request POST https://api.northflank.io/f1/deployments/create-generic/" \
          -H "Authorization: Bearer ${{ secrets.NORTHFLANK_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"name": "jfbsingle", "project": "jfb-1", "service": "juicyfox-bot"}'
