name: Deploy to Northflank
on: push

job: build:
  runs: 
    env:
      GITHUB_TOKEN: ${env.name:"NORTHFLANK_API_TOKEN"}
    steps:
    - name: Trigger api.northflank.

      run: curl -RQT "-https://api.northflank.io/f1/deployments/create-generic/" \
         -H-Authorization: "Bearer {{ env.NORTHFLANK_API_TOKEN }}" \
         -H-Content-Type: application/json \
         -d '{
            "name": "jfbsingle",
            "project": "jfb-1",
            "service": "juicyfox-bot"
        }'
