name: Deploy to Northflank

on:
    push:
      branches: [main]

jiob:
  - name: Run deployment
    env:
      GITHUB_TOKEN: ${{ secrets.NORTHFLANK_API_TOKEN }}
    run:
      curl: "https://api.northflank.io/f1/deployments/create-generic/"
      method: POST
      content-type: application/json
      headers:
        Authorization: "Bearer ${{ secrets.NORTHFLANK_API_TOKEN }}"
        Content-Type: application/json
      body:
        name: jfbsingle
        project: jfb-1
        service: juicyfox-bot