name: Verify Repo Structure

on:
  push:
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run structure verifier
        run: |
          chmod +x scripts/verify_structure.py
          python scripts/verify_structure.py
